version: 2
updates:
  # Root package.json
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies

  # Frontend
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - frontend

  # Backend
  - package-ecosystem: npm
    directory: "/backend"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - backend

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - dependencies
      - github-actions
